Remove Floatting Action Menu when Rescuer
Ph0tonic/SDP_Projet pull request #284
Opened 2020-06-06 13:29 UTC by AlexisTabin

2020-06-06 18:24 UTC, Ph0tonic requested changes

2020-06-06 18:24 UTC, Ph0tonic commented on app/src/androidTest/java/ch/epfl/sdp/ui/maps/MapActivityTest.kt
> +    fun rescuerDoesNotSeeFloattingMenuButton() {
Single t for floating

2020-06-07 21:36 UTC, Ph0tonic approved these changes

2020-06-08 10:09 UTC, Nchappui approved these changes

2020-06-08 15:13 UTC, merged